# Generated by Django 3.2.13 on 2022-06-03 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_auto_20220603_1721'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorsignal',
            name='contestant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='races.racecontestantqualification'),
        ),
        migrations.AlterField(
            model_name='sensorsignal',
            name='sensor_mark',
            field=models.CharField(choices=[('start', 'start'), ('finish', 'finish')], max_length=32),
        ),
    ]
