# Generated by Django 3.2.13 on 2022-06-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_racebracket_level'),
        ('sensors', '0002_auto_20220603_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorsignal',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='races.race'),
            preserve_default=False,
        ),
    ]
