# Generated by Django 3.2.13 on 2022-06-03 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceContestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('helmet_number', models.IntegerField(blank=True, null=True)),
                ('qualification_number', models.IntegerField(blank=True, null=True)),
                ('qualification_time_ms', models.IntegerField(blank=True, null=True)),
                ('is_amateur', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=True)),
                ('is_master', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='races.race')),
            ],
        ),
        migrations.CreateModel(
            name='RaceBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Amateur'), (1, 'Open'), (2, 'Master')], db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_bracket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_brackets', to='races.racebracket')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='races.race')),
            ],
        ),
        migrations.CreateModel(
            name='BracketContestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='races.racebracket')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='races.racecontestant')),
            ],
        ),
    ]
