# Generated by Django 3.2.13 on 2022-06-03 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_bracketcontestant_racebracket_racecontestant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racecontestant',
            name='qualification_time_ms',
        ),
        migrations.CreateModel(
            name='RaceContestantQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='races.racecontestant')),
            ],
        ),
    ]
