# Generated by Django 3.2.13 on 2022-06-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_auto_20220603_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='racebracket',
            name='level',
            field=models.SmallIntegerField(default=0),
        ),
    ]
