# Generated by Django 3.2.13 on 2022-06-05 17:01

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_racebracket_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='file',
            field=models.FileField(null=True, upload_to=common.utils.upload_to),
        ),
    ]
