# Generated by Django 3.2.13 on 2022-06-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_race_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
