# Generated by Django 3.2.13 on 2022-06-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_race_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='file',
            new_name='background_image',
        ),
    ]
